# file      : examples/xhtml/buildfile
# copyright : Copyright (c) 2013-2017 Code Synthesis Tools CC
# license   : MIT; see accompanying LICENSE file

import libs = libstudxml%lib{studxml}

exe{driver}: {hxx cxx}{*} $libs doc{README}
