# file      : tests/roundtrip/buildfile
# copyright : Copyright (c) 2013-2017 Code Synthesis Tools CC
# license   : MIT; see accompanying LICENSE file

import libs = libstudxml%lib{studxml}

exe{driver}: cxx{driver} $libs test{testscript}

define xml: file
xml{*}: extension = xml

./: exe{driver} xml{attribute characters followup-1 followup-2 namespace}
