# file      : tests/roundtrip/buildfile
# copyright : Copyright (c) 2013-2019 Code Synthesis Tools CC
# license   : MIT; see accompanying LICENSE file

import libs = libstudxml%lib{studxml}

exe{driver}: {hxx cxx}{*} $libs testscript

define xml: file
xml{*}: extension = xml

./: exe{driver} xml{*}
