# file      : examples/hybrid/buildfile
# copyright : Copyright (c) 2013-2018 Code Synthesis Tools CC
# license   : MIT; see accompanying LICENSE file

import libs = libstudxml%lib{studxml}

exe{driver}: {hxx cxx}{*} $libs doc{README}
exe{driver}: file{position.xml}: test.input = true
