# file      : examples/inheritance/buildfile
# copyright : Copyright (c) 2013-2017 Code Synthesis Tools CC
# license   : MIT; see accompanying LICENSE file

import libs = libstudxml%lib{studxml}

exe{driver}: cxx{driver} {cxx hxx}{position} $libs doc{README}
exe{driver}: test.input = position.xml
