# file      : doc/buildfile
# copyright : Copyright (c) 2013-2019 Code Synthesis Tools CC
# license   : MIT; see accompanying LICENSE file

define css: file

css{*}:
{
  extension = css
  install = doc/
}

./: doc{intro.xhtml} css{default}
