# file      : examples/buildfile
# copyright : Copyright (c) 2013-2017 Code Synthesis Tools CC
# license   : MIT; see accompanying LICENSE file

./: hybrid/ inheritance/ performance/ persistence/ processing/ roundtrip/ \
    xhtml/ doc{README}

