# file      : examples/buildfile
# copyright : Copyright (c) 2013-2017 Code Synthesis Tools CC
# license   : MIT; see accompanying LICENSE file

d = hybrid/ inheritance/ performance/ persistence/ processing/ roundtrip/ \
    xhtml/

./: $d doc{README}
include $d
