# file      : examples/performance/buildfile
# copyright : Copyright (c) 2013-2019 Code Synthesis Tools CC
# license   : MIT; see accompanying LICENSE file

import libs = libstudxml%lib{studxml}

exe{driver}: {hxx cxx}{* -expat -gen} $libs doc{README} file{*.xsd}
exe{driver}: file{test-50k.xml}: test.input = true
