# file      : examples/performance/buildfile
# copyright : Copyright (c) 2013-2014 Code Synthesis Tools CC
# license   : MIT; see accompanying LICENSE file

import libs = libstudxml%lib{studxml}

exe{driver}: cxx{driver} {cxx hxx}{time} $libs doc{README} file{test.xsd}
exe{driver}: test.input = test-50k.xml
